### ISSUE TITLE
Applied changes

### ISSUE THREAD

**Issue by sheri-thomson** [sheri-thomson/stylish-beets#1]
@thomasjbradley

Hello,

I'm going through the main css and making changes but they aren't applying to my live website, and I'm having the same issue with the main.css being misspelled. I feel like I've gone over it multiple times but don't see the error.

Thanks,
Sheri

**Comment by thomasjbradley** [comment]
Did you figure it out? I'm seeing CSS working when I look at the site online.

**Comment by sheri-thomson** [comment]
@thomasjbradley 
Sorry for the delay in response. It is sort of working.. some of the CSS is syncing but other elements aren't. Im trying adjust the fig caption but the css is not changing it. 

```
figcaption {
  font-size: .8rem;
  font-style: italic;
  text-align: center;
}
```

Also I'm feeling so lost in this assignment :(

**Comment by thomasjbradley** [comment]
*Re: figcaption—*

The CSS for the `<figcaption>` looks correct and when I check in the browser I can see that it's working.

---

*Re: feeling lost—*

It's looking really good; it seems like you're progressing well. Are there questions that I can try to answer to help you out?

**Comment by sheri-thomson** [comment]
I was able to attend the lab today and get through the last few adjustments in order to push it through markbot but I feel like once I finish a task, I wouldn't really be able to explain how I did it or do it again. This assignment had me guessing a lot and I would rather feel more confident moving forward. I'm reviewing videos and reading all the code used in tutorials to gain more scope, but the workload is getting heavy and so many new things..ahh all at once!! lol..

**Comment by thomasjbradley** [comment]
Okay—wonderful!

Yeah, there are lots of new things—unfortunately that can't be helped. Sorry.

At this early in coding I don't really expect anybody to know what their doing and have a perfect understanding and direction. The fact that you can try-fail-try-solve the problem is exactly what's important right now. The trying is the thing—the understanding will come with practice.

**Comment by sheri-thomson** [comment]
Okay, cool! 
Thanks :)
I really like coding!

**Comment by thomasjbradley** [comment]
Coding—yeah!
